language: go
go:
    - 1.6
go_import_path: kego.io/
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
addons:
  apt:
    packages:
      - nodejs
install:
  - go get -u github.com/gopherjs/gopherjs
  - go get -t -v ./...
script:
  - go run cmd/gotests/gotests.go -js
after_success:
  - bash <(curl -s https://codecov.io/bash)
