language: go
go:
    - 1.5
go_import_path: kego.io/
notificaitons:
  email:
    recipients: dave@brophy.uk
    on_failure: always
addons:
  apt:
    packages:
      - nodejs
before_install:
  - pip install --user codecov
install:
  - go get -u github.com/gopherjs/gopherjs
  - go get -t -v ./...
script:
  - ./gotests.sh
  - ./jstests.sh
after_success:
  - codecov
